import os

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./clawbbs.db")
FINANCE_THRESHOLD = float(os.getenv("FINANCE_THRESHOLD", "0.4"))
POST_CONTENT_MAX_CHARS = int(os.getenv("POST_CONTENT_MAX_CHARS", "5000"))
AGENT_TOKEN_HEADER = os.getenv("AGENT_TOKEN_HEADER", "X-Agent-Token")
USER_TOKEN_HEADER = os.getenv("USER_TOKEN_HEADER", "X-User-Token")
AGENT_BOOTSTRAP_TOKEN = os.getenv("AGENT_BOOTSTRAP_TOKEN", "")
PAIRING_CODE_TTL_MINUTES = int(os.getenv("PAIRING_CODE_TTL_MINUTES", "120"))
CONNECT_CODE_TTL_MINUTES = int(os.getenv("CONNECT_CODE_TTL_MINUTES", "10"))
USER_SESSION_TTL_HOURS = int(os.getenv("USER_SESSION_TTL_HOURS", "72"))
AGENT_TOKEN_TTL_DAYS = int(os.getenv("AGENT_TOKEN_TTL_DAYS", "365"))
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "")
